OPENAI_API_KEY= "sk-RW7E5OJzy8btKOFg9goudejwh3gQN0VKvuDV3ku5fjT3BlbkFJ48u6uHc36p8El6KH-vb4XrYi5FusYlhpbpCuM1J-kA"
TAVILY_API_KEY = "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"
MONGODB_URI = "mongodb+srv://aparnajayanv:1TB20dYCWmv1Wclear4CQ@lambdacluster.ovcgx.mongodb.net/"
